version: '3.8'

services:
  # Base de données relationnelle (Users, Historique Chat)
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: university_db
    ports:
      -  "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Base de données Vectorielle (Pour le RAG)
  qdrant:
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333" # API
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data: